microcloud charm v0.1
canonical/charm-microcloud pull request #2
Opened 2023-09-14 13:11 UTC by gabrielmougard

This is the initial work for the Microcloud MAAS charm. 

**As of now the charm achieves the following**:
* Support for `microceph` and `microovn`.
* A cluster is bootstraped with the microcloud `--auto` flag.
* Three nodes and four nodes cluster initialization (I didn't test for bigger configurations because of hardware limitations but I don't see any systemic code issues that wouldn't allow it)
* One unit at a time scale-up: 3 to 4 scale-up tested successfully

**Roadmap items to achieve for 0.2**:
* ~~https://github.com/canonical/charm-microcloud/issues/3~~
* https://github.com/canonical/charm-microcloud/issues/4
* https://github.com/canonical/charm-microcloud/issues/5

**Roadmap items to achieve for 1.0**:
* https://github.com/canonical/charm-microcloud/issues/6
* https://github.com/canonical/charm-microcloud/issues/7

Closes #3

2023-09-14 13:21 UTC, tomponline commented
I'll leave this up to @masnax and @simondeziel

2023-09-14 15:37 UTC, tomponline commented on setup/lxd.conf
> +    size: 150GB
@gabrielmougard why is this hardcoded to this size?

2023-09-14 15:37 UTC, tomponline commented on setup/lxd.conf
> +    ipv4.address: 10.10.10.1/24
why is this hardcoded?

2023-09-14 15:37 UTC, tomponline commented on setup/lxd.conf
> +    ipv6.address: none
why is ipv6 disabled?

2023-09-14 15:43 UTC, gabrielmougard commented on setup/lxd.conf
> +    size: 150GB
We might be creating a lot of machines (4 or more) with at least two disk (I try to give between 10 and 20GiB for each), and one machine for the juju controller. But of course, if we don't use the disks as part of this setup and we just want to test their availability, we could reduce that number.

2023-09-14 15:46 UTC, tomponline commented on setup/lxd.conf
> +    size: 150GB
So what is lxd.conf used for? Is it used when deploying the charm, or is this just a demo script?

2023-09-14 15:46 UTC, gabrielmougard commented on setup/lxd.conf
> +    ipv4.address: 10.10.10.1/24
This setup is just meant to be a 'demo' use case so I thought we could just fix these values to have the same instance IP addresses in MAAS all the time and not burden the user with too much parameterization steps

2023-09-14 15:47 UTC, tomponline commented on setup/lxd.conf
> +    ipv4.address: 10.10.10.1/24
Can we rename this directory to demo then please for clarity.

2023-09-14 15:47 UTC, gabrielmougard commented on setup/lxd.conf
> +    ipv6.address: none
good question. I guess the 'demo' simply did not make use of it.. But we could of course change this.

2023-09-14 15:49 UTC, tomponline commented on setup/lxd.conf
> +    ipv6.address: none
As both these IP subnets are going into the repo, they extend beyond your earlier demo, so suggest leaving them out so an automatic subnet is generated.

Do they need to be extracted and passed elsewhere?

2023-09-14 15:55 UTC, gabrielmougard commented on setup/lxd.conf
> +    ipv4.address: 10.10.10.1/24
sure

2023-09-14 15:56 UTC, gabrielmougard commented on setup/lxd.conf
> +    size: 150GB
simply for demo, I'll rename the folder so that it is more explicit.

2023-09-14 15:58 UTC, gabrielmougard commented on setup/lxd.conf
> +    ipv6.address: none
in the `setup/maas-setup.sh` script, II declare `export SUBNET=10.10.10.0/24` so it assumes that there is the network ipv4 declared in the same subnet

2023-09-15 08:08 UTC, tomponline commented on setup/lxd.conf
> +    ipv6.address: none
OK I see. In that case can you define the config file inside the script itself so you can use the SUBNET var in the config piped to LXD. You can use a similar approach to this:

https://documentation.ubuntu.com/lxd/en/latest/howto/instances_routed_nic_vm/

`cat <<EOF | lxc ... -`

2023-09-15 08:10 UTC, gabrielmougard commented on setup/lxd.conf
> +    ipv6.address: none
thanks, I'll look into it

2023-09-25 19:34 UTC, simondeziel commented on src/charm.py
> +        lxd_client = pylxd.Client()
If that's the only thing using `pylxd`, I'd vote for removing it and replacing it with a call to `lxc list --all-projects`. The reason to push back on `pylxd` is that is makes the charm super slow to build due to needing to compile a lot of `rust` bits and effectively makes the charm arch specific. Also, there are other places where `lxc` is directly called like to get a cluster list.

2023-09-25 19:34 UTC, simondeziel commented on src/charm.py
> +                self.set_peer_data_str(self.unit, "new_node", "")
Is the absence of `clustered` the same as `new_node=True`? If yes, could we lose `new_node`.

2023-09-25 19:34 UTC, simondeziel commented on src/charm.py
> +            self.set_peer_data_str(self.app, "num_clustered_units", str(num_clustered_units - 1))
Is this function mostly a debugging aid?

2023-10-10 10:31 UTC, roosterfish reviewed
I was able to provision the cluster on the first try using the charm. Looks good.

Being more verbose when deploying the charm without the required number of three machines could be helpful. Is there a way to block the cluster creation if the number of units is < 3 and print an appropriate error message? Additionally it may be worth waiting until the required number of units is present.

Regarding the `operator_libs_linux/snap` library maybe we could add something to the GitHub actions to ensure this gets updated on a regular basis? 

Edit: This already exists for the `lxd` charm: https://github.com/canonical/charm-lxd/blob/main/.github/workflows/update-libs.yml

2023-10-19 13:27 UTC, gabrielmougard commented on config.yaml
> +    default: false
I usually leave the key to its default

2023-10-19 16:04 UTC, gabrielmougard commented on src/charm.py
> +                self.set_peer_data_str(self.unit, "new_node", "")
These two states do not exactly serve the same purpose. `new_node` is only used for the initial cluster bootstrap:  we typically wait for the moment where all the peers + the leader are in that state to init the cluster. When they are not new anymore (which mean they are `clustered`), we set `new_node=""`. But a non-clustered node (because it has been disconnected from the original cluster and is not connected to its peers anymor) is not necessarily a `new_node`

2023-10-19 16:08 UTC, gabrielmougard commented on src/charm.py
> +            self.set_peer_data_str(self.app, "num_clustered_units", str(num_clustered_units - 1))
For now yes. I intended to use that logic for later but I can remove it.

2023-10-19 16:41 UTC, gabrielmougard commented
@roosterfish updated

2023-10-19 18:44 UTC, simondeziel commented on src/charm.py
> +                self.set_peer_data_str(self.unit, "new_node", "")
I don't quite get it, sorry. By a "non-clustered" node, do you mean a node that was once clustered but was removed and want to join again?

2023-10-20 08:30 UTC, roosterfish requested changes
Looks good, thanks for adding the charm library updates already in this PR. I just added a few small suggestions regarding nomenclature.

2023-10-20 08:30 UTC, roosterfish commented on README.md
> +# Microcloud charm for MAAS
```suggestion
# MicroCloud charm for MAAS
```

Let's try to be consistent with the naming of MicroCloud in camel case according to the official page https://microcloud.is/

2023-10-20 08:30 UTC, roosterfish commented on README.md
> +This charm deploys Microcloud on a MAAS cluster with Juju.
Again the camel case version of MicroCloud.

2023-10-20 08:30 UTC, roosterfish commented on demo/maas-setup.sh
> +# juju add-model microcloud-maas maas-cloud
It's just the commented out docs but I think this model is redundant since you create a new one called `microcloud` down below which is then used to deploy the charm.

2023-10-20 08:30 UTC, roosterfish commented on metadata.yaml
> +  Microcloud can automatically configure LXD, Ceph, and OVN across a set of servers.
Again the camel case version of MicroCloud.

2023-10-20 08:30 UTC, roosterfish commented on metadata.yaml
> +      A debug version of the Microcloud binary or a tarball of architecture specific
Again the camel case version of MicroCloud, same as above.

2023-10-20 08:30 UTC, roosterfish commented on metadata.yaml
> +      A custom Microcloud snap or tarball of architecture specific snaps to install.
MicroCloud :)

2023-10-20 08:30 UTC, roosterfish commented on pyproject.toml
> +description = "Machine Charm for Microcloud"
Again the camel case version of MicroCloud.

2023-10-20 08:30 UTC, roosterfish commented on src/charm.py
> +"""Microcloud charm."""
Again the camel case version of MicroCloud :)

2023-10-20 08:30 UTC, roosterfish commented on src/charm.py
> +class MaasMicrocloudCharmCharm(CharmBase):
```suggestion
class MaasMicroCloudCharm(CharmBase):
```

Looks like `Charm` is doubled here.

2023-10-20 08:30 UTC, roosterfish commented on src/charm.py
> +        logger.info("Installing the Microcloud charm")
MicroCloud camel case.

2023-10-20 08:30 UTC, roosterfish commented on src/charm.py
> +        # Install Microcloud itself
🐪, also a few more in the lines below.

2023-10-20 08:30 UTC, roosterfish commented on src/charm.py
> +                logger.warning(
To be consistent with the other error messages in the charm could you please remove the dots at the end where applicable?

2023-10-23 10:44 UTC, roosterfish commented on src/charm.py
> +                self.set_peer_data_str(self.unit, "new_node", "")
Couldn't the line be changed to something like this to remove the need for `new_node`:

```python
new_peers = [self.peers.data[unit].get("clustered") == "False" for unit in self.peers.units]
```

This way `new_node` doesn't have to be unset after the cluster is formed and when creating the relation you could initially do `self.set_peer_data_str(self.unit, "clustered", "False")`. 

If the node gets accidentally disconnected from the cluster, is this something the charm needs to handle?

2023-11-06 18:26 UTC, simondeziel approved these changes
Thanks!

2023-11-09 13:52 UTC, roosterfish approved these changes

2023-11-10 08:27 UTC, merged